"""
app/models/report.py
Clinical report — generated by doctor, optionally shared with patient.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Enum, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


class Report(Base):
    __tablename__ = "reports"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    doctor_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    patient_id: Mapped[str] = mapped_column(String, nullable=False, index=True)
    diagnosis_id: Mapped[str | None] = mapped_column(String, nullable=True)
    report_type: Mapped[str] = mapped_column(
        Enum("progress", "treatment_plan", "discharge", "follow_up", "lab_summary",
             name="report_type_enum"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    patient_friendly_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    treatment_plan: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    clinic_name: Mapped[str | None] = mapped_column(String, nullable=True)
    clinic_address: Mapped[str | None] = mapped_column(String, nullable=True)
    is_shared_with_patient: Mapped[bool] = mapped_column(Boolean, default=True)
    generated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
